name: Auto Contribution

on:
  schedule:
    - cron: "0 4,10,16,20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make update
        run: |
          echo "Update at $(date)" >> activity_log.txt

      - name: Commit and push
        run: |
          git config user.name "ThePriyanshuDas"
          git config user.email "Ypriyanshudas030@gmail.com"
          
          git add activity_log.txt
          
          git diff --staged --quiet || git commit -m "Auto update: $(date)"
          
          git push