name: Auto Contribution

on:
  schedule:
    - cron: "0 4,10,16,20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Update at $(date)" >> activity_log.txt

      - name: Commit and push safely
        run: |
          git config user.name "ThePriyanshuDas"
          git config user.email "priyanshudas030@gmail.com"

          git add activity_log.txt

          # Check if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update: $(date)"
            git push origin main
          fi